name: Manual Deploy to AWS ECR

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 014498632254.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t my-web-app:latest.

      - name: Tag Docker Image
        run: |
          docker tag my-web-app:latest 014498632254.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-web-app:jackpiro

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 014498632254.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-web-app:latest
