name: Deploy to Localhost

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Local Nginx on Port 8080
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Nginx
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nginx


      - name: Configure Nginx to Serve on Port 8080
        run: |
          sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
          echo 'server_name localhost;' | sudo tee -a /etc/nginx/sites-available/default
          sudo nginx -t && sudo systemctl reload nginx

      - name: Deploy Website Files
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
          sudo systemctl restart nginx
