name: Build and Run on Nginx

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nginx
        run: sudo apt-get update && sudo apt-get install -y nginx

      - name: Configure Nginx for Port 8080
        run: |
          sudo sed -i 's/listen 80 default_server;/listen 8080;/' /etc/nginx/sites-available/default
          sudo sed -i 's|root /var/www/html;|root /usr/share/nginx/html;|' /etc/nginx/sites-available/default

      - name: Copy Application Files
        run: |
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r . /usr/share/nginx/html/

      - name: Restart Nginx
        run: sudo systemctl restart nginx

      - name: Verify Nginx is Running
        run: curl -I http://localhost:8080 || (echo "Nginx failed to start" && exit 1)
